language: ruby
cache: bundler
before_install:
#  - sudo apt-get install mediainfo
   - sudo apt-get install libmms0
   - wget https://mediaarea.net/download/binary/libzen0/0.4.37/libzen0_0.4.37-1_amd64.xUbuntu_14.04.deb
   - sudo dpkg -i libzen0_0.4.37-1_amd64.xUbuntu_14.04.deb
   - wget https://mediaarea.net/download/binary/libmediainfo0/18.08.1/libmediainfo0_18.08.1-1_amd64.xUbuntu_14.04.deb
   - sudo dpkg -i libmediainfo0_18.08.1-1_amd64.xUbuntu_14.04.deb
   - wget https://mediaarea.net/download/binary/mediainfo/18.08.1/mediainfo_18.08.1-1_amd64.xUbuntu_14.04.deb
   - sudo dpkg -i mediainfo_18.08.1-1_amd64.xUbuntu_14.04.deb
sudo: false
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
